### ISSUE TITLE
java.io.IOException: Cannot download 'https://github.com/HotswapProjects/HotswapAgent/releases/download/1.2.0/hotswap-agent-1.2.0.jar': Status: 404

### ISSUE THREAD

**Issue by thomedw** [dmitry-zhuravlev/hotswap-agent-intellij-plugin#15]
I think it should have been ```https://github.com/HotswapProjects/HotswapAgent/releases/download/RELEASE-1.2.0/hotswap-agent-1.2.0.jar``` instead of ```https://github.com/HotswapProjects/HotswapAgent/releases/download/1.2.0/hotswap-agent-1.2.0.jar```

```
java.io.IOException: Cannot download 'https://github.com/HotswapProjects/HotswapAgent/releases/download/1.2.0/hotswap-agent-1.2.0.jar': Status: 404
com.hotswap.agent.plugin.services.DownloadManagerException: java.io.IOException: Cannot download 'https://github.com/HotswapProjects/HotswapAgent/releases/download/1.2.0/hotswap-agent-1.2.0.jar': Status: 404
	at com.hotswap.agent.plugin.services.DownloadManager$downloadAgentJarAsynchronously$1$downloadTask$1.run(DownloadManager.kt:80)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:713)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:157)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:543)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:488)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:94)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:144)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl$2.run(ProgressManagerImpl.java:165)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:315)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: Cannot download 'https://github.com/HotswapProjects/HotswapAgent/releases/download/1.2.0/hotswap-agent-1.2.0.jar': Status: 404
	at com.intellij.platform.templates.github.DownloadUtil$1.process(DownloadUtil.java:178)
	at com.intellij.util.io.HttpRequests.lambda$doProcess$0(HttpRequests.java:418)
	at com.intellij.util.net.ssl.CertificateManager.runWithUntrustedCertificateStrategy(CertificateManager.java:349)
	at com.intellij.util.io.HttpRequests.doProcess(HttpRequests.java:418)
	at com.intellij.util.io.HttpRequests.process(HttpRequests.java:398)
	at com.intellij.util.io.HttpRequests.access$100(HttpRequests.java:63)
	at com.intellij.util.io.HttpRequests$RequestBuilderImpl.connect(HttpRequests.java:266)
	at com.intellij.platform.templates.github.DownloadUtil.a(DownloadUtil.java:169)
	at com.intellij.platform.templates.github.DownloadUtil.downloadContentToFile(DownloadUtil.java:152)
	at com.hotswap.agent.plugin.services.DownloadManager.doDownload(DownloadManager.kt:140)
	at com.hotswap.agent.plugin.services.DownloadManager.access$doDownload(DownloadManager.kt:48)
	at com.hotswap.agent.plugin.services.DownloadManager$downloadAgentJarAsynchronously$1$downloadTask$1.run(DownloadManager.kt:78)
	... 13 more
Caused by: com.intellij.util.io.HttpRequests$HttpStatusException: Status: 404. Status=404, Url=https://github.com/HotswapProjects/HotswapAgent/releases/download/1.2.0/hotswap-agent-1.2.0.jar
	at com.intellij.util.io.HttpRequests.openConnection(HttpRequests.java:527)
	at com.intellij.util.io.HttpRequests.access$300(HttpRequests.java:63)
	at com.intellij.util.io.HttpRequests$RequestImpl.getConnection(HttpRequests.java:292)
	at com.intellij.platform.templates.github.DownloadUtil$1.process(DownloadUtil.java:173)
	... 24 more
```

**Comment by thomedw** [comment]
Oh, it duplicates #14 . Please close this.
