### ISSUE TITLE
Can't download hotswap-agent-1.2.0.jar

### ISSUE THREAD

**Issue by rherrick** [dmitry-zhuravlev/hotswap-agent-intellij-plugin#18]
Got the message:

`11:07 AM	New HotSwapAgent version available: Download and apply new version of HotSwapAgent. (show balloon)`

Error appears with command-line download attempt:

`$ http --download https://github.com/HotswapProjects/HotswapAgent/releases/download/1.2.0/hotswap-agent-1.2.0.jar
HTTP/1.1 404 Not Found`

The full error message is:

`java.io.IOException: Cannot download 'https://github.com/HotswapProjects/HotswapAgent/releases/download/1.2.0/hotswap-agent-1.2.0.jar': Status: 404
com.hotswap.agent.plugin.services.DownloadManagerException: java.io.IOException: Cannot download 'https://github.com/HotswapProjects/HotswapAgent/releases/download/1.2.0/hotswap-agent-1.2.0.jar': Status: 404
	at com.hotswap.agent.plugin.services.DownloadManager$downloadAgentJarAsynchronously$1$downloadTask$1.run(DownloadManager.kt:80)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:750)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:157)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:580)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:525)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:85)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:144)
	at com.intellij.openapi.progress.impl.CoreProgressManager$4.run(CoreProgressManager.java:395)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:305)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: Cannot download 'https://github.com/HotswapProjects/HotswapAgent/releases/download/1.2.0/hotswap-agent-1.2.0.jar': Status: 404
	at com.intellij.platform.templates.github.DownloadUtil$1.process(DownloadUtil.java:178)
	at com.intellij.util.io.HttpRequests.lambda$doProcess$0(HttpRequests.java:418)
	at com.intellij.util.net.ssl.CertificateManager.runWithUntrustedCertificateStrategy(CertificateManager.java:335)
	at com.intellij.util.io.HttpRequests.doProcess(HttpRequests.java:418)
	at com.intellij.util.io.HttpRequests.process(HttpRequests.java:398)
	at com.intellij.util.io.HttpRequests.access$100(HttpRequests.java:63)
	at com.intellij.util.io.HttpRequests$RequestBuilderImpl.connect(HttpRequests.java:266)
	at com.intellij.platform.templates.github.DownloadUtil.download(DownloadUtil.java:169)
	at com.intellij.platform.templates.github.DownloadUtil.downloadContentToFile(DownloadUtil.java:152)
	at com.hotswap.agent.plugin.services.DownloadManager.doDownload(DownloadManager.kt:140)
	at com.hotswap.agent.plugin.services.DownloadManager.access$doDownload(DownloadManager.kt:48)
	at com.hotswap.agent.plugin.services.DownloadManager$downloadAgentJarAsynchronously$1$downloadTask$1.run(DownloadManager.kt:78)
	... 13 more
Caused by: com.intellij.util.io.HttpRequests$HttpStatusException: Status: 404. Status=404, Url=https://github.com/HotswapProjects/HotswapAgent/releases/download/1.2.0/hotswap-agent-1.2.0.jar
	at com.intellij.util.io.HttpRequests.openConnection(HttpRequests.java:527)
	at com.intellij.util.io.HttpRequests.access$300(HttpRequests.java:63)
	at com.intellij.util.io.HttpRequests$RequestImpl.getConnection(HttpRequests.java:292)
	at com.intellij.platform.templates.github.DownloadUtil$1.process(DownloadUtil.java:173)
	... 24 more`

**Comment by JWT007** [comment]
This has been driving me crazy for weeks... every IntelliJ start prompts me to download the new HotSwapAgent which does not exist at the given URL

**Comment by hibissscus** [comment]
Sorry guys for this we will fix this broken download-url soon, please be patient because it has to be to be approved by JetBrains plugin committee.

**Comment by Plasticable** [comment]
Try to download hotswap-agent manually from [here](https://github.com/HotswapProjects/HotswapAgent/releases/download/RELEASE-1.2.0/hotswap-agent-1.2.0.jar)  and put it to `[idea_home]\config\plugins\hotswap-agent-intellij-plugin\lib\agent`. You can discover your `[idea_home]` by reading [this](https://intellij-support.jetbrains.com/hc/en-us/articles/206544519-Directories-used-by-the-IDE-to-store-settings-caches-plugins-and-logs).
